SYMPTOMS = [
    'unsteadiness', 
    'sunken eyes', 
    'patches in throat', 
    'enlarged thyroid', 
    'movement stiffness', 
    'irritability', 
    'malaise', 
    'rusty sputum', 
    'loss of smell', 
    'painful walking', 
    'inflammatory nails', 
    'dark urine', 
    'scurring', 
    'diarrhoea', 
    'loss of appetite', 
    'spotting  urination', 
    'fluid overload', 
    'palpitations', 
    'knee pain', 
    'extra marital contacts', 
    'family history', 
    'ulcers on tongue', 
    'muscle pain', 
    'irritation in anus', 
    'fast heart rate', 
    'pain in anal region', 
    'loss of balance', 
    'irregular sugar level', 
    'yellowish skin', 
    'history of alcohol consumption', 
    'redness of eyes', 
    'dehydration', 
    'swelling joints', 
    'muscle weakness', 
    'cold hands and feets', 
    'watering from eyes', 
    'mood swings', 
    'weakness of one body side', 
    'cramps', 
    'yellow crust ooze', 
    'yellowing of eyes', 
    'pain during bowel movements', 
    'restlessness', 
    'constipation', 
    'blister', 
    'stiff neck', 
    'nodal skin eruptions', 
    'visual disturbances', 
    'prominent veins on calf', 
    'swollen blood vessels', 
    'altered sensorium', 
    'receiving blood transfusion', 
    'swollen extremeties', 
    'obesity', 
    'continuous sneezing', 
    'stomach bleeding', 
    'acute liver failure', 
    'back pain', 
    'dischromic  patches', 
    'pus filled pimples', 
    'red sore around nose', 
    'itching', 
    'red spots over body', 
    'hip joint pain', 
    'mucoid sputum', 
    'shivering', 
    'internal itching', 
    'abdominal pain', 
    'weakness in limbs', 
    'slurred speech', 
    'stomach pain', 
    'belly pain', 
    'joint pain', 
    'weight loss', 
    'silver like dusting', 
    'polyuria', 
    'lethargy', 
    'sweating', 
    'vomiting', 
    'spinning movements', 
    'bloody stool', 
    'distention of abdomen', 
    'nausea', 
    'indigestion', 
    'anxiety', 
    'passage of gases', 
    'mild fever', 
    'bruising', 
    'receiving unsterile injections', 
    'puffy face and eyes', 
    'phlegm', 
    'acidity', 
    'chest pain', 
    'skin peeling', 
    'pain behind the eyes', 
    'burning micturition', 
    'weight gain', 
    'sinus pressure', 
    'small dents in nails', 
    'dizziness', 
    'drying and tingling lips', 
    'swelled lymph nodes', 
    'neck pain', 
    'throat irritation', 
    'continuous feel of urine', 
    'fatigue', 
    'lack of concentration', 
    'congestion', 
    'blood in sputum', 
    'blurred and distorted vision', 
    'headache', 
    'yellow urine', 
    'cough', 
    'depression', 
    'runny nose', 
    'increased appetite', 
    'swollen legs', 
    'abnormal menstruation', 
    'high fever', 
    'toxic look (typhos)', 
    'brittle nails', 
    'skin rash', 
    'muscle wasting', 
    'excessive hunger', 
    'breathlessness', 
    'chills', 
    'coma', 
    'bladder discomfort', 
    'swelling of stomach', 
    'foul smell of urine', 
    'blackheads']

DISEASES = [
    'Arthritis', 
    'Typhoid', 
    'AIDS', 
    'Chronic cholestasis', 
    'Urinary tract infection', 
    'Peptic ulcer disease', 
    'Hepatitis B', 
    'Hypoglycemia', 
    'Migraine', 
    'Jaundice', 
    'Hepatitis D', 
    'Osteoarthristis', 
    'Diabetes ', 
    'Chicken pox', 
    'Alcoholic hepatitis', 
    'Common Cold', 
    'Heart attack', 
    'Cervical spondylosis', 
    'Allergy', 
    'Malaria', 
    'Drug Reaction', 
    'Hyperthyroidism', 
    'Gastroenteritis', 
    'Psoriasis', 
    'Bronchial Asthma', 
    'Dengue', 
    'Pneumonia', 
    'Dimorphic hemmorhoids(piles)', 
    '(vertigo) Paroymsal  Positional Vertigo', 
    'Fungal infection', 
    'Hypothyroidism', 
    'hepatitis A', 
    'Hepatitis C', 
    'Impetigo', 
    'Varicose veins', 
    'GERD', 
    'Hypertension ', 
    'Acne', 
    'Hepatitis E', 
    'Paralysis (brain hemorrhage)', 
    'Tuberculosis']